name: ledet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.11.0
  - torchvision=0.12.0
  - pip
  - pip:
    - torchaudio==0.11.0
    - mmcv-full==1.7.1
    - lvis@git+https://github.com/lvis-dataset/lvis-api
    - mmdet==2.28.0
    - -r requirements.txt
    - -e .
